### ISSUE TITLE
`Show` instance for `Json`

### ISSUE THREAD

**Issue by menelaos** [purescript-contrib/purescript-argonaut-core#30]
Was it a deliberate decision to remove the `Show` instance for `Json` in https://github.com/purescript-contrib/purescript-argonaut-core/commit/83dd71ff982a68176c42b0cae06932c3cd79a6a1? I stumbled upon this due to some broken tests that were using `(===)` from `purescript-strongcheck`, which relies on `Show`.

**Comment by garyb** [comment]
It was deliberate, yeah. It breaks the idea of `Show` printing something equivalent to the PureScript code that constructs it.

**Comment by menelaos** [comment]
That's what I feared ;-) Do you have an example of where the `Show` instance might pose a problem?

**Comment by thomashoneyman** [comment]
@menelaos I don't believe it's necessarily that `Show` causes a problem in the code produced, but rather than the point of the `Show` type class is for debugging and printing out a PureScript representation of data and types rather than for formatting strings.

If you want to 'print' JSON values use the [`stringify` function](https://github.com/purescript-contrib/purescript-argonaut-core/blob/1a9a4d87d97645f5fa0414a60f84f2bdae58ccd5/src/Data/Argonaut/Core.purs#L201), which is further described [in the MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) (if you need it :))

**Comment by cdepillabout** [comment]
Let me try to make an argument for bringing back the `Show` instance for `Json`.

I (and I imagine most people?) mainly use `Show` for debugging.  In order to `show` a `Json`, you have to call `stringify`.  While this isn't a _huge_ problem, it is a small papercut that I get again and again when working with PureScript.  Adding a `Show Json` instance would remove this small papercut for me.

@garyb and @thomashoneyman say above:

> It breaks the idea of Show printing something equivalent to the PureScript code that constructs it.

> the point of the Show type class is for debugging and printing out a PureScript representation of data and types rather than for formatting strings.

However, the [docs on `Show`](https://pursuit.purescript.org/packages/purescript-prelude/4.1.1/docs/Data.Show) say the following

> While not required, it is recommended that for any expression `x`, the `String` `show x` be executable PureScript code which evaluates to the same value as the expression `x`.

I think the "while not required" is important.  While it would be great if `Show Json` could produce valid PureScript code, `Show Json` is still pretty helpful for debugging if it doesn't produce valid PureScript code.

Having `Show` produce valid code is pretty important in the Haskell ecosystem because of the prevalence of `Read`.  And non-conforming instances are one of the reasons for libraries like [pretty-simple](https://github.com/cdepillabout/pretty-simple).  However, there is no `Read` in PureScript, so I don't know how strong of a reason this is for PureScript.

I imagine some people like to `Show` data types, and then copy and paste them back to the repl to play around with them.  It is unfortunate that you can't do this with `Show Json`, but removing the instance isn't helping the situation.  It wouldn't be possible to copy-and-paste the output JSON whether you use `Show Json`, or just `stringify`.

Given this, I think having the `Show Json` instance slightly reduces the small repeated mental overhead of having to import `stringify`.

**Comment by flip111** [comment]
@cdepillabout i agree with you. It's more than this though, it's not just about importing `stringify` but when you have a type like

```purescript
data MyType = MyType String Json
```

You have to write a custom `Show` implementation for it because the generic one doesn't work. And show for record breaks all together once you put a json type in.

```purescript
data MyRecord=
  { name :: String
  , my_json :: Json
  }
```

There are always ways around it, like newtyping and wrapping/unwrapping the new type everywhere in your code.

I prefer the minimal amount of friction when debugging and i'm not particularly concerned how the output looks like. Any output is better than having no `Show` instance.

One maintainer said he had no problem adding a proposed implementation https://github.com/purescript-contrib/purescript-argonaut-core/issues/37#issuecomment-543862069 Let us re-open the relevant issues until other maintainers respond and after that a PR can be made.
