### ISSUE TITLE
Requesting Show Instance

### ISSUE THREAD

**Issue by eric-corumdigital** [purescript-contrib/purescript-argonaut-core#37]
```
showJson ∷ Json → String
showJson = Argo.caseJson
  (\_ → "jsonNull")
  (\x → "(fromBoolean " <> show x <> ")")
  (\x → "(fromNumber " <> show x <> ")")
  (\x → "(fromString " <> show x <> ")")
  (\x → "(fromArray " <> show (map showJson x) <> ")")
  (\x → "(fromObject " <> show (map showJson x) <> ")")
```

**Comment by thomashoneyman** [comment]
This isn't quite the same thing, but the [`stringify` function](https://github.com/purescript-contrib/purescript-argonaut-core/blob/1a9a4d87d97645f5fa0414a60f84f2bdae58ccd5/src/Data/Argonaut/Core.purs#L201) can be used to print `Json` to a string. If you just need to make comparisons, perhaps that would work?

That said, you're suggesting a traditional Show instance, not something that produces valid JSON, so I'm assuming that would not suffice. I'd like to defer to @garyb and others as to why, exactly, the original Show instance was removed. If I remember correctly it was because the Show class is meant to represent how PureScript represents things, which your suggestion does, whereas the old Show produced stringified JSON.

I do not have a problem adding a Show instance for debugging purposes, but I'd appreciate weigh-in from other maintainers before adding it.

**Comment by thomashoneyman** [comment]
I'm going to close this for inactivity, but I can reopen the issue if needed.
