### ISSUE TITLE
Unify `JsonDecodeError` types into this library

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/purescript-argonaut-core#55]
`JsonDecodeError` is defined in two separate places:
- [`purescript-codec-argonaut`](https://pursuit.purescript.org/packages/purescript-codec-argonaut/7.1.0/docs/Data.Codec.Argonaut#t:JsonDecodeError), the original definition
- [`purescript-argonaut-codecs`](https://pursuit.purescript.org/packages/purescript-argonaut-codecs/8.1.0/docs/Data.Argonaut.Decode.Error#t:JsonDecodeError), a port of the original one to this library

`purescript-argonaut-codecs` defines [`parsJson`](https://pursuit.purescript.org/packages/purescript-argonaut-codecs/8.1.0/docs/Data.Argonaut.Decode.Parser#v:parseJson), but `codec-argonaut` does not.

Can we define both the `JsonDecodeError` type and `parseJson` in this library so that the two other libraries can be used interchangeably?

**Comment by garyb** [comment]
I don't think it quite belongs in this library, since codec errors are not a core part of "json".

I'd like to figure this out: https://github.com/purescript-contrib/purescript-argonaut-codecs/pull/85 before committing to a shared representation too.

I've also been working on reviving/finalising my `purescript-json` library a bit recently (which is intended to finally be an official core library for JSON), so I'll probably take a look at errors again as part of a `codec-json` library I'm making for it. `codec-json` may end up much the same as `codec-argonaut`, but there's a few things I'm experimenting with to try and simplify or improve aspects of it.
